name: "workflow context"
on: ['push']
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: getting repo name via context
      env:
        REPOSITORY_NAME: ${{github.repository}}
      run: echo  "REPOSITORY- $REPOSITORY_NAME"
